# Generated by Django 3.2.25 on 2024-09-02 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convention', '0002_alter_convention_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('discription', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent', models.BooleanField(default=False)),
                ('single_use', models.BooleanField(default=False)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convention.convention')),
            ],
        ),
        migrations.CreateModel(
            name='DealerRegistrationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('number_tables', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convention.convention')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('is_credit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Confirmation code')),
                ('registration_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('badge_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('email_me', models.BooleanField(default=False, verbose_name='Opt-in for occasional email communication from the convention')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('volunteer', models.BooleanField(default=False, verbose_name='Contact me for volunteering opportunities')),
                ('volunteer_phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number (only required if volunteering)')),
                ('q1', models.CharField(blank=True, max_length=255, null=True)),
                ('q2', models.CharField(blank=True, max_length=255, null=True)),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('private_notes', models.TextField(blank=True, null=True)),
                ('private_check_in', models.BooleanField(default=False)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_in_on', models.DateTimeField(blank=True, null=True, verbose_name='When checked in')),
                ('status', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid'), (2, 'Payment In Progress'), (3, 'Refunded'), (4, 'Reg Rejected')], default=0)),
                ('needs_print', models.IntegerField(choices=[(0, 'No, printed'), (1, 'Yes, new reg'), (2, 'Yes, upgraded')], default=1, verbose_name='Badge needs printed?')),
                ('reported_on', models.DateTimeField(blank=True, null=True, verbose_name='Included in paper report on')),
                ('ip', models.GenericIPAddressField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='reg_avatars/')),
                ('emergency_contact', models.CharField(blank=True, help_text='Optionally, provide an contact person in case of emergency', max_length=255, null=True)),
                ('dealer_registration_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.dealerregistrationlevel', verbose_name='Dealer Tables')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('badge_name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes_addition', models.TextField(blank=True, null=True)),
                ('private_notes_addition', models.TextField(blank=True, null=True)),
                ('private_check_in', models.BooleanField(default=False)),
                ('notify_registration_group', models.BooleanField(default=True)),
                ('notify_board_group', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('background', models.CharField(max_length=255)),
                ('added_text', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(max_length=7)),
                ('opens', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convention.convention')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationTempAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='tmp_avatars/')),
                ('new_badge_name', models.CharField(blank=True, max_length=32, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('current_registration_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='registration.registrationlevel')),
                ('upgrade_registration_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades_from', to='registration.registrationlevel')),
            ],
        ),
        migrations.CreateModel(
            name='ShirtSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Swag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('sizes', models.BooleanField(default=False)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convention.convention')),
            ],
        ),
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_override', models.CharField(blank=True, max_length=32, null=True)),
                ('positions', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(choices=[(1, 'Chair'), (2, 'Vice-chair'), (3, 'Treasurer'), (4, 'Board'), (5, 'Staff')], default=5)),
                ('avatar_virtual_filename', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff_avatars/')),
                ('approved', models.BooleanField(default=False)),
                ('extra', models.TextField(blank=True, null=True)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convention.convention')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationUpgradePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active_date', models.DateTimeField()),
                ('registration_upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationupgrade')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationSwag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(default=True)),
                ('backordered', models.BooleanField(default=False)),
                ('backorder_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.shirtsize')),
                ('swag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.swag')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_open', models.BooleanField(default=True)),
                ('badge_number_style', models.IntegerField(choices=[(1, 'Assigned when printed'), (2, 'Assigned at registration')], default=2)),
                ('badge_offset', models.IntegerField(default=0)),
                ('convention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='convention.convention')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(max_length=15)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('top_of_queue', models.DateTimeField(blank=True, null=True)),
                ('additional_data', models.CharField(max_length=40)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationLevelSwag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_register_before', models.DateTimeField(blank=True, null=True)),
                ('registration_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationlevel')),
                ('swag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.swag')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationLevelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active_date', models.DateTimeField()),
                ('registration_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationlevel')),
            ],
        ),
        migrations.AddField(
            model_name='registrationlevel',
            name='swag',
            field=models.ManyToManyField(through='registration.RegistrationLevelSwag', to='registration.Swag'),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.registrationlevel'),
        ),
        migrations.AddField(
            model_name='registration',
            name='shirt_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.shirtsize'),
        ),
        migrations.AddField(
            model_name='registration',
            name='swag',
            field=models.ManyToManyField(through='registration.RegistrationSwag', to='registration.Swag'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_state', models.IntegerField(choices=[(1, 'Paid'), (2, 'Refund Requested'), (3, 'Refunded')], default=1)),
                ('payment_level_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_received', models.DateTimeField(auto_now_add=True)),
                ('payment_extra', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('refund_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_requested', models.DateTimeField(blank=True, null=True)),
                ('refund_processed', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.paymentmethod')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunded_by_user', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
            ],
        ),
        migrations.CreateModel(
            name='CouponUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.couponcode')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
            ],
        ),
        migrations.AddField(
            model_name='couponcode',
            name='force_dealer_registration_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.dealerregistrationlevel'),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='force_registration_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.registrationlevel'),
        ),
        migrations.CreateModel(
            name='BadgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_on', models.DateTimeField(auto_now_add=True)),
                ('printed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printed_by_user', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
                ('registration_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registration.registrationlevel')),
            ],
        ),
        migrations.AddIndex(
            model_name='registrationqueue',
            index=models.Index(fields=['queue_name', 'id'], name='registratio_queue_n_d76d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationqueue',
            index=models.Index(fields=['registration'], name='registratio_registr_f0aa56_idx'),
        ),
    ]
